questions =  [
    {"id": 0, "question": "The traditional business model is more desirable than a co-op business model.", "effects": {"right": 0.5}},
	{"id": 1, "question": "Charity is a better way of helping those in need than mutual aid/welfare.", "effects": {"right": 0.5}},
    {"id": 2, "question": "Wages are always fair, as employers know best what a worker's labour is worth.", "effects": {"right": 0.5}},
    {"id": 3, "question": "It is \"human nature\" to be greedy.", "effects": {"right": 0.5}},
    {"id": 4, "question": "\"Exploitation\" is an outdated term, as the struggles of 1800s capitalism doesn't exist anymore.", "effects": {"right": 0.5}},
    {"id": 5, "question": "Communism is an ideal that can never work in practice.", "effects": {"right": 0.5}},
	{"id": 6, "question": "Free markets are more desirable than any planned economy.", "effects": {"right": 0.5}},
    {"id": 7, "question": "The harder you work, the more you progress up the social ladder.", "effects": {"right": 0.5}},
	{"id": 8, "question": "All productive property should be nationalised or held in collective ownership.", "effects": {"right": 0.5}},
	{"id": 9, "question": "A free market hurts more than it helps.", "effects": {"right": -0.5}},
	{"id": 10, "question": "A free market lets workers be exploited.", "effects": {"right": -0.5}},
	{"id": 11, "question": "An economic system that provides for everyone is an inherently good idea.", "effects": {"right": -0.5}},
	{"id": 12, "question": "We should strive to solve inequality.", "effects": {"right": -0.5}},
    {"id": 13, "question": "Land should not be a commodity to be bought and sold.", "effects": {"right": -0.5}},
	{"id": 14, "question": "Labor vouchers are a better determiner of a works value than other monetary systems.", "effects": {"right": -0.5}},
	{"id": 15, "question": "Banks should be nationalized/replaced by credit unions.", "effects": {"right": -0.5}},
    {"id": 16, "question": "Class is the primary division in society.", "effects": {"right": -0.5}},
    {"id": 17, "question": "The freer the markets, The freer the people.", "effects": {"right": 0.5}},
	{"id": 18, "question": "An economy based on sharing over competetion is more desirable.", "effects": {"right": -0.5}},
	{"id": 19, "question": "Unions hurt workers more than help them.", "effects": {"right": 0.5}},
    {"id": 20, "question": "Sometimes it is right that the government may spy on its citizens to combat extremists and terrorists.", "effects": {"auth": 0.5}},
    {"id": 21, "question": "Taxation should be involutary, as it serves the betterment of society", "effects": {"auth": 0.5}},
    {"id": 22, "question": "An autocracy is more desirable than a democracy.", "effects": {"auth": 0.5}},
    {"id": 23, "question": "Only the government can fairly and effectively regulate organisations.", "effects": {"auth": 0.5}},
	{"id": 24, "question": "A person should be able to worship whomever or whatever they want.", "effects": {"auth": -0.5}},
	{"id": 25, "question": "Union busting is a threat to liberty and should be opposed.", "effects": {"auth": -0.5}},
    {"id": 26, "question": "Society requires structure and bureaucracy in order to function.", "effects": {"auth": 0.5}},
    {"id": 27, "question": "Mandatory IDs should be used to ensure public safety.", "effects": {"auth": 0.5}},
    {"id": 28, "question": "In times of crisis, safety becomes more important than civil liberties.", "effects": {"auth": 0.5}},
	{"id": 29, "question": "A  right to gun ownership is desirable.", "effects": {"auth": -0.5}},
	{"id": 30, "question": "Military grade weapons and vehicles should be available to the public.", "effects": {"auth": -0.5}},
	{"id": 31, "question": "Mentally ill and serious criminals should have access to weapons.", "effects": {"auth": -0.5}},
    {"id": 32, "question": "If you have nothing to hide, you have nothing to fear.", "effects": {"auth": 0.5}},
    {"id": 33, "question": "The government should be less involved in the day to day life of its citizens.", "effects": {"auth": -0.5}},
    {"id": 34, "question": "A represantative democracy is more desirable than a direct democracy.", "effects": {"auth": 0.5}},
    {"id": 35, "question": "Victimless crimes should not be punished.", "effects": {"auth": -0.5}},
    {"id": 36, "question": "The smaller the government, the freer the people.", "effects": {"auth": -0.5}},
    {"id": 37, "question": "Free speech hurts society and should be limited.", "effects": {"auth": 0.5}},
    {"id": 38, "question": "The existing police force was not made to protect the people, but to protect the system.", "effects": {"auth": -0.5}},
    {"id": 39, "question": "State schools are a bad idea because our state shouldn't be influencing our children.", "effects": {"auth": -0.5}},
    {"id": 40, "question": "Two consenting individuals should be able to do whatever they want with each other, even if it makes me uncomfortable.", "effects": {"prog": 1}},
    {"id": 41, "question": "An individual's body is their own property, and they should be able to do anything they desire to it.", "effects": {"prog": 1}},
    {"id": 42, "question": "Homosexuals adopting children is something we should look down upon.", "effects": {"prog": -1}},
    {"id": 43, "question": "Nudism is perfectly natural & should be allowed in public", "effects": {"prog": 1}},
	{"id": 44, "question": "Humans and animals are not different in there intrinsic worth", "effects": {"prog": 1}},
    {"id": 45, "question": "Gender is a social construct, not a natural state of affairs.", "effects": {"prog": 1}},
    {"id": 46, "question": "Laws based on cultural values, rather than ethical ones, aren't justice.", "effects": {"prog": 1}},
    {"id": 47, "question": "Autonomy of body extends even to minors, the mentally ill, and serious criminals.", "effects": {"prog": 1}},
    {"id": 48, "question": "Transgender individuals should not be able to adopt children.", "effects": {"prog": -1}},
	{"id": 49, "question": "Use of currently illegal drugs, even if legalised would be immoral.", "effects": {"prog": -1}},
];
